name: Run Automation Tests

on:
  schedule:
    - cron: "0 19 * * *"   # Runs daily at 12:30 AM IST
  workflow_dispatch:       # Manual run button

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.14.3'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
 
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Verify Chrome
      run: |
        which google-chrome
        google-chrome --version
    
    - name: Install ChromeDriver
      run: |
        sudo apt-get install -y chromium-chromedriver

    - name: Run Tests
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: |
        pytest